version: "2"

services:
  db:
    image: deadrobots/pixi:datastore
    container_name: pixidb
    ports:
      - "27017:27017"
      - "28017:28017"

  app:
    image: pixi-app
    container_name: pixi-app
    ports:
      - "8000:8000"
    restart: unless-stopped
